name: 'Changelog'
on:
  pull_request:
    branches:
    - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Create Release
      #   uses: mikepenz/action-gh-release@v0.2.0-a03 #softprops/action-gh-release
      #   with:
      #     body: ${{steps.build_changelog.outputs.changelog}}